# Generated by Django 5.2.7 on 2025-11-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_orderitem_userprofile_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
